AWSTemplateFormatVersion: '2010-09-09'
Description: 'stack: {{stackName}} | stage: {{stage}} | deployed by Kes'
Resources:
  NethopeSitrepDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: NethopeSitrepDB
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.small
      Engine: postgres
      EngineVersion: 9.6.2
      MasterUsername: {{rds.username}}
      MasterUserPassword: {{rds.password}}
